/*
 * This file is generated by jOOQ.
 */
package com.github.srcmaxim.jooq;


import com.github.srcmaxim.jooq.tables.City;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.city</code>.
     */
    public static final City CITY = City.CITY;
}
